# Laboratorio Investigación de Operaciones
Basada en la ayudantía de Machine Learning, Anthony Cho.

#### Ayudante: Francisco Ferrada

**Tema**: Introduccion a Python 

#### Asignacion de variables

In [13]:
a = 1
b = 'hola'
c = 1.0
## Imprimir las variables
print(a)
print(b)
print(c)
## Imprimir tipo de dato almacenado en la variable
print( type(a) )
print( type(b) )
print( type(c) )

1
hola
1.0
<class 'int'>
<class 'str'>
<class 'float'>


### Algunas operaciones basicas

In [3]:
## Suma
a = a+10
#a +=10
print(a)

## Resta
a = a-10
#a-=10
print(a)

## Multiplicacion
a = a*10
#a*=10
print(a)

## Division
a = a/10
#a/=10
print(a)
type(a)

11
1
10
1.0


float

### Listas
Recordar que las listas solo son un conjunto de elementos agrupados, pueden tener distinto tipo de dato alojado en una misma lista. Incluso listas adentro de la lista.

In [16]:
lista_nueva = ['perro', 24, False]
lista_nueva
for i in lista_nueva:
    print(i)

perro
24
False


In [3]:
# Crear lista
eventos = ['dormir', 'comer', 'correr', 'escapar',['lista','en','lista']]
cualquierCosa = ['Modelo', 'PQC', 1500000]
lista = [1,4,2,5,6,7,8,9,0,5,3,2]

In [4]:
# Imprimir una lista
print('eventos: ', eventos)

eventos:  ['dormir', 'comer', 'correr', 'escapar', ['lista', 'en', 'lista']]


In [7]:
# Imprimir las dos listas en forma simple
print(f'cualquierCosa:\n{cualquierCosa}')

cualquierCosa:
['Modelo', 'PQC', 1500000]


In [6]:
# Imprimir las dos listas en un formato personalizado
print('Lista 1: {}\nLista 2: {}'.format(eventos, cualquierCosa))

Lista 1: ['dormir', 'comer', 'correr', 'escapar', ['lista', 'en', 'lista']]
Lista 2: ['Modelo', 'PQC', 1500000]


#### Algunas operaciones con listas

In [8]:
# Adjuntar al final de la lista un elemento
lista.append(100)
print('lista: ', lista)

lista:  [1, 4, 2, 5, 6, 7, 8, 9, 0, 5, 3, 2, 100]


In [9]:
# Adjuntar una lista a otra lista como un elemento
lista.append(eventos[4])
print('lista: ', lista)

lista:  [1, 4, 2, 5, 6, 7, 8, 9, 0, 5, 3, 2, 100, ['lista', 'en', 'lista']]


In [11]:
# Extender una lista con los elementos de otra lista
lista = [1,4,2,5,6,7,8,9,0,5,3,2]
lista2 = [3,523,5,9,6]

lista.extend(lista2)
print('lista: ', lista)

lista:  [1, 4, 2, 5, 6, 7, 8, 9, 0, 5, 3, 2, 3, 523, 5, 9, 6]


In [12]:
# Consultar posicion del primer elemento que coincida con el numero 7 en la lista
lista.index(7)

5

In [13]:
# Contar cuantas repeticiones hay del numero 8 en la lista
lista.count(8)

1

In [14]:
# Insertar el elemento 100 en el indice 3 de la lista
lista.insert(3, 100)
print(lista)

[1, 4, 2, 100, 5, 6, 7, 8, 9, 0, 5, 3, 2, 3, 523, 5, 9, 6]


In [15]:
# Remover la primera aparicion en la lista que coincida con el numero 2.
lista.remove(2)
print(lista)

[1, 4, 100, 5, 6, 7, 8, 9, 0, 5, 3, 2, 3, 523, 5, 9, 6]


In [16]:
# Eliminar el ultimo elemento de la lista
lista.pop()
print(lista)

[1, 4, 100, 5, 6, 7, 8, 9, 0, 5, 3, 2, 3, 523, 5, 9]


In [17]:
# Eliminar el elemento localizado en el indice 2 de la lista
lista.pop(2)
print(lista)

[1, 4, 5, 6, 7, 8, 9, 0, 5, 3, 2, 3, 523, 5, 9]


### Diccionarios

In [18]:
# Crear un diccionario
costos = {'Desayuno': 50, 
          'Almuerzo': 100,
          'Cena': {'Suave': 40, 
                   'Intermedio': 60, 
                   'Heavy': 120}
          }
costos

{'Almuerzo': 100,
 'Cena': {'Heavy': 120, 'Intermedio': 60, 'Suave': 40},
 'Desayuno': 50}

In [19]:
##Visualizar las llaves de un diccionario
costos.keys()

dict_keys(['Desayuno', 'Almuerzo', 'Cena'])

In [20]:
## Visualizar las llaves del diccionario 'Cena', el cual se encuentra al interior del diccionario 'costos'
costos['Cena'].keys()

dict_keys(['Suave', 'Intermedio', 'Heavy'])

In [21]:
contacto = {}
contacto['Nombre'] = 'Francisco'
contacto['telefono'] = '+56900000001'
contacto['email'] = 'fco@pmail.com'
contacto['Ayudante'] = ['Python', 'Laboratorio de IO']

print(contacto)

{'Nombre': 'Francisco', 'telefono': '+56900000001', 'email': 'fco@pmail.com', 'Ayudante': ['Python', 'Laboratorio de IO']}


In [22]:
# Acceso a elemento del diccionario
costos['Desayuno']

50

In [23]:
costos['Cena']

{'Heavy': 120, 'Intermedio': 60, 'Suave': 40}

In [24]:
costos['Cena']['Suave']

40

### Condicional IF, IF-ELSE, IF-ELIF-...ELIF-ELSE

In [25]:
a = 20
print('Valor de a: {}'.format(a))

Valor de a: 20


In [26]:
## Uso de un solo IF
if a <30:
    print("El valor de a es menor que 30")

El valor de a es menor que 30


In [27]:
## Uso del IF-ELSE
if a < 10:
    print("El valor de a es menor que 10")
else:
    print("El valor de a es mayor o igual que 10")

El valor de a es mayor o igual que 10


In [28]:
## Uso del IF-ELSE anidados
if a < 10:
    print("El valor de a es menor que 10")
else:
    if a < 20:
        print("El valor de a es menor que 20")
    else:
        print("El valor de a es mayor o igual que 20")


El valor de a es mayor o igual que 20


In [29]:
## Uso del IF-ELIF-ELSE
if a < 10:
    print("El valor de a es menor que 10")
elif a < 20:
    print("El valor de a es menor que 20")
else:
    print("El valor de a es mayor o igual que 20")


El valor de a es mayor o igual que 20


### Bucles

In [30]:
## Calcular el tamaño de la lista
print(eventos)
N = len(eventos)
N

['dormir', 'comer', 'correr', 'escapar', ['lista', 'en', 'lista']]


5

In [31]:
## uso del for por elemento
for itera in eventos:
    print(itera)

dormir
comer
correr
escapar
['lista', 'en', 'lista']


In [32]:
j = range(10)
for i in j:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [33]:
## Uso del for por indice
for i in range(N):
    print(eventos[i])

dormir
comer
correr
escapar
['lista', 'en', 'lista']


In [34]:
## Uso del while
i = 0
while i<N:
    print(eventos[i])
    
    ## Aumentar el indice una unidad
    i = i+1

dormir
comer
correr
escapar
['lista', 'en', 'lista']


### Crear una funcion personalizada

In [36]:
def Mi_funcion(a1,b1):
    if type(a1) == list and type(b1) == list:
        print(f'Dado que son listas, el largo del elemento resultante es: {len(a1)+len(b1)}')
        return a1+b1
    if type(a1) == np.ndarray and type(b1) == np.ndarray:
        if len(a1) != len(b1):
            print('La operacion no es factible por problemas de dimensionalidad.')
        else:
            print(f'Dado que son arreglos, el largo del elemento resultante es: {max(len(a1),len(b1))}')
            return a1+b1
    if (type(a1) == np.ndarray and type(b1) != np.ndarray) or (type(a1) == list and type(b1) != list):
        print('La operacion no puede ser realizada, ya que los elementos no coinciden en su naturaleza.')

In [37]:
k = [1,2,3]
l = [4,5,6]
Mi_funcion(k,l)

Dado que son listas, el largo del elemento resultante es: 6


[1, 2, 3, 4, 5, 6]

### Cargar una libreria completa
En este escenario solo utilizaremos la libreria numpy, la cual es útil para desarrollar operaciones matematicas con arreglos y/o matrices.
La sintaxis de importación considera lo siguiente:
import numpy as np
Importa la librería "numpy" con el nombre np.

Esto es útil cuando queramos llamar a las funciones de las librerías, ya que siempre tendremos que poner el nombre de la librería antes de la funcion que queramos llamar que esté al interior de esta.

Las librerias que comunmente ocuparemos en el curso son:

`import numpy as np`    Principalmente para desarrollar operaciones matematicas.

`import matplotlib.pyplot as plt`    Para crear gráficos.

`import pandas as pd`      Para realizar lectura de datos e importar data.


### Cargar una funcion especifica de una libreria
En el caso en que necesitemos importar una función específica de una librería, se puede hacer con la siguiente sintaxis:



```
from libreria import funcion
```
Ejemplo: 
```
from numpy import linspace
```



In [4]:
import numpy as np

In [41]:
k = np.array([1,2,3])
l = np.array([4,5,6])
c = Mi_funcion(k,l)
c

Dado que son arreglos, el largo del elemento resultante es: 3


array([5, 7, 9])

In [42]:
k = np.array([1,2,3])
l = [4,5,6]
Mi_funcion(k,l)

La operacion no puede ser realizada, ya que los elementos no coinciden en su naturaleza.


#### Operaciones con numpy

In [40]:
## Definir listas
A = [[1,2,3], [0,1,2]]
b = [2, 3, 1]

## Conversion de listas a arreglos de numpy
A = np.array(A)
b = np.array(b)

print('Matriz A:\n{}'.format(A))
print('\nVector b:\n{}'.format(b))

Matriz A:
[[1 2 3]
 [0 1 2]]

Vector b:
[2 3 1]


In [ ]:
# forma de la matriz
print(f'Forma de la matriz A: {A.shape}')
print('Forma de la matriz b: {}'.format(b.shape))

Forma de la matriz A: (2, 3)
Forma de la matriz b: (3,)


In [ ]:
# Numero de fila de una matriz
print(f'Numero de filas de la matriz A: {A.shape[0]}')
print(f'Numero de columnas de la matriz A: {A.shape[1]}')

Numero de filas de la matriz A: 2
Numero de columnas de la matriz A: 3


In [ ]:
# Numero de elemento de una matriz
print('Total elemento de la matriz: {}'.format(A.size))

Total elemento de la matriz: 6


In [ ]:
# Longitud de un vector
print('Longitud del vector: {}'.format( len(b) ))

Longitud del vector: 3


In [ ]:
# Operaciones punto a punto (numpy)
A+b #Suma cada fila de la matriz A con el vector b.

array([[3, 5, 4],
       [2, 4, 3]])

In [ ]:
# producto de la matriz A con el vector b
A.dot(b)

array([11,  5])

In [ ]:
# Buscar el maximo de la matrix
A.max()

3

In [ ]:
# Buscar el maximo por columna
A.max(axis=0)

array([1, 2, 3])

In [ ]:
# Buscar el maximo por fila
A.max(axis=1)

array([3, 2])

In [ ]:
# Llamar a todos los elementos de una columna
for i in range(A.shape[1]):
    print(f'Columna {i}: {A[:,i]}')

Columna 0: [1 0]
Columna 1: [2 1]
Columna 2: [3 2]


In [ ]:
# Llamar a todos los elementos de una fila
for i in range(A.shape[0]):
    print(f'Columna {i}: {A[i,:]}')

In [ ]:
# Convertir la matriz es un vector
A.ravel()

array([1, 2, 3, 0, 1, 2])

In [ ]:
# Redimensionar una matriz
A.reshape((3, 2))

array([[1, 2],
       [3, 0],
       [1, 2]])

### Generacion de números aleatorios


In [130]:
np.random.uniform()

0.6141231645643385

#### Generación de vector con numeros aleatorios

In [131]:
np.random.uniform(0,1,10)

array([0.84545116, 0.32550748, 0.40262445, 0.21839394, 0.81378253,
       0.62919521, 0.63791002, 0.06369707, 0.13691843, 0.5043634 ])

#### Generación de matriz con numeros aleatorios

In [143]:
np.random.uniform(0,1,(10,10))
#from tabulate import tabulate
#print(tabulate(np.random.uniform(0,1,(10,10))))

array([[0.69122644, 0.98518425, 0.49387906, 0.83432927, 0.53747831,
        0.06246169, 0.28274445, 0.24447419, 0.34026283, 0.60100833],
       [0.82554832, 0.15769143, 0.1505801 , 0.94913856, 0.11187162,
        0.21260167, 0.13686096, 0.11114994, 0.84675429, 0.2308813 ],
       [0.52880016, 0.37646383, 0.54314154, 0.4234762 , 0.46806062,
        0.20858417, 0.04188241, 0.41561072, 0.48510142, 0.7030916 ],
       [0.18172678, 0.88329725, 0.96787315, 0.17607248, 0.65284599,
        0.4122815 , 0.81066655, 0.50534604, 0.90090491, 0.24121649],
       [0.55141945, 0.42289854, 0.24768599, 0.53792137, 0.94135697,
        0.79931088, 0.6200406 , 0.29081195, 0.0306563 , 0.99509161],
       [0.22701243, 0.37269426, 0.72417338, 0.80085475, 0.05835394,
        0.73370128, 0.28910149, 0.36843226, 0.22703854, 0.92408875],
       [0.09067213, 0.77653695, 0.31254553, 0.18317149, 0.99158412,
        0.47144365, 0.98747089, 0.8123165 , 0.32186573, 0.90215289],
       [0.46049666, 0.91065728, 0.5640979

### Generar una matriz de 0

In [142]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])